name: Build & Push Docker image
on:
  push:
    branches: [ main ]
    tags: ['v1.0.0']
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract project/version
        id: meta
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/mini-vol
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "tag=latest" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.tag }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.image }}:buildcache
          cache-to: type=registry,ref=${{ steps.meta.outputs.image }}:buildcache,mode=max

      - name: Create and push git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v1.0.0
          git push origin v1.0.0